language: java
jdk:
  - openjdk15
os: linux
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
after_success:
  - echo "Success. Move to server."
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_deploy:
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_COMMIT
  - echo "$DEPLOY_KEY" | ssh-add - > /dev/null
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target/santanizer-0.0.1-SNAPSHOT.jar $DEPLOY_PATH/santanizer.jar
  on:
    all_branches: true
after_deploy:
  - ssh -T $DEPLOY_PATH 'service santanizer restart && systemctl daemon-reload'